/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as QuizShareCodeRouteImport } from './routes/quiz.$shareCode'
import { Route as DashboardTemplatesRouteImport } from './routes/dashboard.templates'
import { Route as DashboardQuizzesRouteImport } from './routes/dashboard.quizzes'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardBatchesIndexRouteImport } from './routes/dashboard.batches.index'
import { Route as DashboardQuizQuizIdRouteImport } from './routes/dashboard.quiz.$quizId'
import { Route as DashboardBatchesBatchIdRouteImport } from './routes/dashboard.batches.$batchId'
import { Route as DashboardQuizQuizIdIndexRouteImport } from './routes/dashboard.quiz.$quizId.index'
import { Route as DashboardBatchesBatchIdIndexRouteImport } from './routes/dashboard.batches.$batchId.index'
import { Route as DashboardQuizQuizIdResultsRouteImport } from './routes/dashboard.quiz.$quizId.results'
import { Route as DashboardQuizQuizIdLiveRouteImport } from './routes/dashboard.quiz.$quizId.live'
import { Route as DashboardBatchesBatchIdAnalyticsRouteImport } from './routes/dashboard.batches.$batchId.analytics'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const QuizShareCodeRoute = QuizShareCodeRouteImport.update({
  id: '/quiz/$shareCode',
  path: '/quiz/$shareCode',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTemplatesRoute = DashboardTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQuizzesRoute = DashboardQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBatchesIndexRoute = DashboardBatchesIndexRouteImport.update({
  id: '/batches/',
  path: '/batches/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQuizQuizIdRoute = DashboardQuizQuizIdRouteImport.update({
  id: '/quiz/$quizId',
  path: '/quiz/$quizId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBatchesBatchIdRoute = DashboardBatchesBatchIdRouteImport.update({
  id: '/batches/$batchId',
  path: '/batches/$batchId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQuizQuizIdIndexRoute =
  DashboardQuizQuizIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardQuizQuizIdRoute,
  } as any)
const DashboardBatchesBatchIdIndexRoute =
  DashboardBatchesBatchIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardBatchesBatchIdRoute,
  } as any)
const DashboardQuizQuizIdResultsRoute =
  DashboardQuizQuizIdResultsRouteImport.update({
    id: '/results',
    path: '/results',
    getParentRoute: () => DashboardQuizQuizIdRoute,
  } as any)
const DashboardQuizQuizIdLiveRoute = DashboardQuizQuizIdLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => DashboardQuizQuizIdRoute,
} as any)
const DashboardBatchesBatchIdAnalyticsRoute =
  DashboardBatchesBatchIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => DashboardBatchesBatchIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/quizzes': typeof DashboardQuizzesRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/quiz/$shareCode': typeof QuizShareCodeRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/batches/$batchId': typeof DashboardBatchesBatchIdRouteWithChildren
  '/dashboard/quiz/$quizId': typeof DashboardQuizQuizIdRouteWithChildren
  '/dashboard/batches/': typeof DashboardBatchesIndexRoute
  '/dashboard/batches/$batchId/analytics': typeof DashboardBatchesBatchIdAnalyticsRoute
  '/dashboard/quiz/$quizId/live': typeof DashboardQuizQuizIdLiveRoute
  '/dashboard/quiz/$quizId/results': typeof DashboardQuizQuizIdResultsRoute
  '/dashboard/batches/$batchId/': typeof DashboardBatchesBatchIdIndexRoute
  '/dashboard/quiz/$quizId/': typeof DashboardQuizQuizIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/quizzes': typeof DashboardQuizzesRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/quiz/$shareCode': typeof QuizShareCodeRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/batches': typeof DashboardBatchesIndexRoute
  '/dashboard/batches/$batchId/analytics': typeof DashboardBatchesBatchIdAnalyticsRoute
  '/dashboard/quiz/$quizId/live': typeof DashboardQuizQuizIdLiveRoute
  '/dashboard/quiz/$quizId/results': typeof DashboardQuizQuizIdResultsRoute
  '/dashboard/batches/$batchId': typeof DashboardBatchesBatchIdIndexRoute
  '/dashboard/quiz/$quizId': typeof DashboardQuizQuizIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/quizzes': typeof DashboardQuizzesRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/quiz/$shareCode': typeof QuizShareCodeRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/batches/$batchId': typeof DashboardBatchesBatchIdRouteWithChildren
  '/dashboard/quiz/$quizId': typeof DashboardQuizQuizIdRouteWithChildren
  '/dashboard/batches/': typeof DashboardBatchesIndexRoute
  '/dashboard/batches/$batchId/analytics': typeof DashboardBatchesBatchIdAnalyticsRoute
  '/dashboard/quiz/$quizId/live': typeof DashboardQuizQuizIdLiveRoute
  '/dashboard/quiz/$quizId/results': typeof DashboardQuizQuizIdResultsRoute
  '/dashboard/batches/$batchId/': typeof DashboardBatchesBatchIdIndexRoute
  '/dashboard/quiz/$quizId/': typeof DashboardQuizQuizIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/dashboard/analytics'
    | '/dashboard/profile'
    | '/dashboard/quizzes'
    | '/dashboard/templates'
    | '/quiz/$shareCode'
    | '/dashboard/'
    | '/dashboard/batches/$batchId'
    | '/dashboard/quiz/$quizId'
    | '/dashboard/batches/'
    | '/dashboard/batches/$batchId/analytics'
    | '/dashboard/quiz/$quizId/live'
    | '/dashboard/quiz/$quizId/results'
    | '/dashboard/batches/$batchId/'
    | '/dashboard/quiz/$quizId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/dashboard/analytics'
    | '/dashboard/profile'
    | '/dashboard/quizzes'
    | '/dashboard/templates'
    | '/quiz/$shareCode'
    | '/dashboard'
    | '/dashboard/batches'
    | '/dashboard/batches/$batchId/analytics'
    | '/dashboard/quiz/$quizId/live'
    | '/dashboard/quiz/$quizId/results'
    | '/dashboard/batches/$batchId'
    | '/dashboard/quiz/$quizId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/dashboard/analytics'
    | '/dashboard/profile'
    | '/dashboard/quizzes'
    | '/dashboard/templates'
    | '/quiz/$shareCode'
    | '/dashboard/'
    | '/dashboard/batches/$batchId'
    | '/dashboard/quiz/$quizId'
    | '/dashboard/batches/'
    | '/dashboard/batches/$batchId/analytics'
    | '/dashboard/quiz/$quizId/live'
    | '/dashboard/quiz/$quizId/results'
    | '/dashboard/batches/$batchId/'
    | '/dashboard/quiz/$quizId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  QuizShareCodeRoute: typeof QuizShareCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/quiz/$shareCode': {
      id: '/quiz/$shareCode'
      path: '/quiz/$shareCode'
      fullPath: '/quiz/$shareCode'
      preLoaderRoute: typeof QuizShareCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/templates': {
      id: '/dashboard/templates'
      path: '/templates'
      fullPath: '/dashboard/templates'
      preLoaderRoute: typeof DashboardTemplatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/quizzes': {
      id: '/dashboard/quizzes'
      path: '/quizzes'
      fullPath: '/dashboard/quizzes'
      preLoaderRoute: typeof DashboardQuizzesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/batches/': {
      id: '/dashboard/batches/'
      path: '/batches'
      fullPath: '/dashboard/batches/'
      preLoaderRoute: typeof DashboardBatchesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/quiz/$quizId': {
      id: '/dashboard/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/dashboard/quiz/$quizId'
      preLoaderRoute: typeof DashboardQuizQuizIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/batches/$batchId': {
      id: '/dashboard/batches/$batchId'
      path: '/batches/$batchId'
      fullPath: '/dashboard/batches/$batchId'
      preLoaderRoute: typeof DashboardBatchesBatchIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/quiz/$quizId/': {
      id: '/dashboard/quiz/$quizId/'
      path: '/'
      fullPath: '/dashboard/quiz/$quizId/'
      preLoaderRoute: typeof DashboardQuizQuizIdIndexRouteImport
      parentRoute: typeof DashboardQuizQuizIdRoute
    }
    '/dashboard/batches/$batchId/': {
      id: '/dashboard/batches/$batchId/'
      path: '/'
      fullPath: '/dashboard/batches/$batchId/'
      preLoaderRoute: typeof DashboardBatchesBatchIdIndexRouteImport
      parentRoute: typeof DashboardBatchesBatchIdRoute
    }
    '/dashboard/quiz/$quizId/results': {
      id: '/dashboard/quiz/$quizId/results'
      path: '/results'
      fullPath: '/dashboard/quiz/$quizId/results'
      preLoaderRoute: typeof DashboardQuizQuizIdResultsRouteImport
      parentRoute: typeof DashboardQuizQuizIdRoute
    }
    '/dashboard/quiz/$quizId/live': {
      id: '/dashboard/quiz/$quizId/live'
      path: '/live'
      fullPath: '/dashboard/quiz/$quizId/live'
      preLoaderRoute: typeof DashboardQuizQuizIdLiveRouteImport
      parentRoute: typeof DashboardQuizQuizIdRoute
    }
    '/dashboard/batches/$batchId/analytics': {
      id: '/dashboard/batches/$batchId/analytics'
      path: '/analytics'
      fullPath: '/dashboard/batches/$batchId/analytics'
      preLoaderRoute: typeof DashboardBatchesBatchIdAnalyticsRouteImport
      parentRoute: typeof DashboardBatchesBatchIdRoute
    }
  }
}

interface DashboardBatchesBatchIdRouteChildren {
  DashboardBatchesBatchIdAnalyticsRoute: typeof DashboardBatchesBatchIdAnalyticsRoute
  DashboardBatchesBatchIdIndexRoute: typeof DashboardBatchesBatchIdIndexRoute
}

const DashboardBatchesBatchIdRouteChildren: DashboardBatchesBatchIdRouteChildren =
  {
    DashboardBatchesBatchIdAnalyticsRoute:
      DashboardBatchesBatchIdAnalyticsRoute,
    DashboardBatchesBatchIdIndexRoute: DashboardBatchesBatchIdIndexRoute,
  }

const DashboardBatchesBatchIdRouteWithChildren =
  DashboardBatchesBatchIdRoute._addFileChildren(
    DashboardBatchesBatchIdRouteChildren,
  )

interface DashboardQuizQuizIdRouteChildren {
  DashboardQuizQuizIdLiveRoute: typeof DashboardQuizQuizIdLiveRoute
  DashboardQuizQuizIdResultsRoute: typeof DashboardQuizQuizIdResultsRoute
  DashboardQuizQuizIdIndexRoute: typeof DashboardQuizQuizIdIndexRoute
}

const DashboardQuizQuizIdRouteChildren: DashboardQuizQuizIdRouteChildren = {
  DashboardQuizQuizIdLiveRoute: DashboardQuizQuizIdLiveRoute,
  DashboardQuizQuizIdResultsRoute: DashboardQuizQuizIdResultsRoute,
  DashboardQuizQuizIdIndexRoute: DashboardQuizQuizIdIndexRoute,
}

const DashboardQuizQuizIdRouteWithChildren =
  DashboardQuizQuizIdRoute._addFileChildren(DashboardQuizQuizIdRouteChildren)

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardQuizzesRoute: typeof DashboardQuizzesRoute
  DashboardTemplatesRoute: typeof DashboardTemplatesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBatchesBatchIdRoute: typeof DashboardBatchesBatchIdRouteWithChildren
  DashboardQuizQuizIdRoute: typeof DashboardQuizQuizIdRouteWithChildren
  DashboardBatchesIndexRoute: typeof DashboardBatchesIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardQuizzesRoute: DashboardQuizzesRoute,
  DashboardTemplatesRoute: DashboardTemplatesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBatchesBatchIdRoute: DashboardBatchesBatchIdRouteWithChildren,
  DashboardQuizQuizIdRoute: DashboardQuizQuizIdRouteWithChildren,
  DashboardBatchesIndexRoute: DashboardBatchesIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  QuizShareCodeRoute: QuizShareCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
